$base           = rgb(191724)
$baseAlpha      = 191724

$surface        = rgb(1f1d2e)
$surfaceAlpha   = 1f1d2e

$overlay        = rgb(26233a)
$overlayAlpha   = 26233a

$muted          = rgb(6e6a86)
$mutedAlpha     = 6e6a86

$subtle         = rgb(908caa)
$subtleAlpha    = 908caa

$text           = rgb(e0def4)
$textAlpha      = e0def4

$love           = rgb(eb6f92)
$loveAlpha      = eb6f92

$gold           = rgb(f6c177)
$goldAlpha      = f6c177

$rose           = rgb(ebbcba)
$roseAlpha      = ebbcba

$pine           = rgb(31748f)
$pineAlpha      = 31748f

$foam           = rgb(9ccfd8)
$foamAlpha      = 9ccfd8

$iris           = rgb(c4a7e7)
$irisAlpha      = c4a7e7

$highlightLow   = rgb(21202e)
$highlightLowAlpha  = 21202e

$highlightMed   = rgb(403d52)
$highlightMedAlpha  = 403d52

$highlightHigh  = rgb(524f67)
$highlightHighAlpha = 524f67

